Basic Search Feature - Google News RSS Feed
MUNComputerScienceSociety/CSS-Slackbot2017 pull request #4
Opened 2017-12-29 18:19 UTC by avinashraja98

The bot will take in anything sent to it and query it at google news which will respond with a rss feed. This is parsed and sent as a response.

2018-01-04 16:04 UTC, stevep1983 commented
Thanks for your contribution! While I am not familiar enough with node.js to review your code, I would suggest attributing https://github.com/apollonian11/reactriot2017-reaction/blob/master/serverApi.js directly in the file that uses it. I am sure that when @moustafaelsisy returns he will check the code out.

Thanks again!

2018-01-13 19:57 UTC, nint8835 commented
I agree with what Steve suggested. In addition:
* Most of the stuff added to the gitignore is not required. You could probably chop out pretty much everything besides the solution files.
* We already have a setup guide in the readme, and as far as I can tell, your usage.md is the same thing, so it isn't required
* I would suggest adding the line `This bot returns the top hit from google news related to the topic sent.` into the readme instead of having it in it's own separate file

2018-01-13 20:24 UTC, nint8835 requested changes
Just a few changes need to be made and then it will be ready to be merged

2018-01-13 20:24 UTC, nint8835 commented on .gitignore
> +
Most of the above changes to the gitignore are not required. Really all you need are the solution files.

2018-01-13 20:24 UTC, nint8835 commented on notes.txt
> +This bot returns the top hit from google news related to the topic sent.
I would suggest moving this line into the readme, instead of having it's own file

2018-01-13 20:24 UTC, nint8835 commented on notes.txt
> +searchArticle.js is from the repo
searchArticle.js is licensed under MIT, which requires you to include it's license and copyright information. I would suggest creating a file along the lines of LICENSE_searchArticle.js.md and copying the contents of [this file](https://github.com/apollonian11/reactriot2017-reaction/blob/master/LICENSE) into it

2018-01-13 20:24 UTC, nint8835 commented on usage.md
> +
The readme file already has installation instructions, so this file is redundant. If you have any changes that need to be made, I would suggest you move them there.

2018-04-23 20:12 UTC, avinashraja98 commented
Changes made as requested. Thanks for the input. Please comment if anything else is required.

2018-09-29 20:29 UTC, nint8835 approved these changes

2018-09-29 20:29 UTC, merged